project:
  type: website
  output-dir: docs

format:
  html:
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 280px
    theme:
      dark: dark.scss
      light: light.scss
    number-sections: true
    number-depth: 2
    toc: true
    toc-title: "Contents"
    toc-depth: 3
    csl: apa.csl
    bibliography: references.bib
  pdf: 
    number-sections: true
    number-depth: 3
    toc: true
    toc-depth: 3
    sansfont: Source Serif Pro
    mainfont: Source Serif Pro
    csl: apa.csl
    bibliography: references.bib
    link-citations: true
    citecolor: SteelBlue
    urlcolor: SteelBlue
    include-in-header:
      text: |
        \usepackage{setspace}
        \setstretch{1.2}
    include-before-body: 
      text: |
        \newpage{}