project:
  type: website
  output-dir: docs

format:
  html:
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 280px
    theme: darkly.scss
    number-sections: true
    number-depth: 2
    toc: true
    toc-title: "Contents"
    toc-depth: 3
    csl: apa.csl
    bibliography: references.bib
  typst:
    section-numbering: 1.1.1
    number-depth: 2
    toc: true
    toc-depth: 2
    csl: apa.csl
    bibliography: references.bib
