project:
  type: default

format:
  pdf:
    toc: true
    number-sections: true
    fig-cap-location: bottom
    citation-location: margin
    fontsize: 11pt
    geometry: margin=2.5cm
    documentclass: article
    colorlinks: true

bibliography: references.bib
lang: en
